[tool.poetry]
name = "Highland-AI"
version = "1.0.6"
description = "Highland-AI"
homepage  = ""
license = ""
authors = [
    "Aawez Khan",
]
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = "^3.10"
unidecode = "^1.3.4"
uvicorn = { extras = ["standard"], version = "^0.18.2" }
gunicorn = "^20.1.0"
tqdm = "^4.64.1"
transformers = "^4.22.1"
python-multipart = "^0.0.5"
ffmpeg-python = "^0.2.0"
fastapi = "^0.85.0"
fastapi-offline-swagger-ui = { git = "https://github.com/ahmetoner/fastapi-offline-swagger-ui" }
torch = "=1.12.0"
openai-whisper = { git = "https://github.com/openai/whisper.git", tag = "v20230124" }

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
